# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JVwrGjLRIWrspeF8Ma02EKod8EezeekS
"""



import joblib
import re
import string
import gradio as gr
import numpy as np

# Load Model
model = joblib.load("sentiment_model.pkl")

# Text Cleaning Function
def clean_text(text):
    text = text.lower()
    text = re.sub('\[.*?\]', '', text)
    text = re.sub('[%s]' % re.escape(string.punctuation), '', text)
    text = re.sub('\w*\d\w*', '', text)
    text = re.sub('[‘’“”…]', '', text)
    text = re.sub('\n', '', text)
    return text

# Prediction Function
def predict_sentiment(text):
    cleaned_text = clean_text(text)
    prediction_probs = model.predict_proba([cleaned_text])[0]  # Get probabilities
    prediction_label = model.classes_[np.argmax(prediction_probs)]  # Get label
    confidence_score = np.max(prediction_probs)  # Get confidence score

    return f"Sentiment: {prediction_label}"

# Gradio Interface
iface = gr.Interface(
    fn=predict_sentiment,
    inputs=gr.Textbox(placeholder="Enter a sentence..."),
    outputs=gr.Textbox(),
    title="Sentiment Analysis",
    description="Enter a text and get the sentiment prediction (positive, negative, or neutral)"
)

# Run the Gradio App
if __name__ == "__main__":
    iface.launch(share=True)